# --- Gateway Connection ---
gateways:
  databricks:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connection
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/databricks/#connection-options
      type: databricks
      # concurrent_tasks: 1
      # register_comments: True
      # pre_ping: False
      # pretty_sql: False
      # schema_differ_overrides: 
      server_hostname: dbc-7147879e-2dea.cloud.databricks.com
      http_path: /sql/1.0/warehouses/872a8c14586ed4cd
      access_token: <DATABRICKS_ACCESS_TOKEN>
      # auth_type: 
      # oauth_client_id: 
      # oauth_client_secret: 
      # catalog: 
      # http_headers: 
      # session_configuration: 
      # databricks_connect_server_hostname: 
      # databricks_connect_access_token: 
      # databricks_connect_cluster_id: 
      # databricks_connect_use_serverless: False
      # force_databricks_connect: False
      # disable_databricks_connect: False
      # disable_spark_session: False
      catalog: car_sales_dev
    state_connection:
      type: duckdb
      database: databricks_state.db

default_gateway: databricks

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: databricks
  start: 2025-08-27 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
